### ISSUE TITLE
[Feature] Center align (Rectangle) Waveform

### ISSUE THREAD

**Issue by timbotimbo** [rutvik110/flutter_audio_waveforms#16]
Right now a RectangleWaveform will have rectangles on either side of the center line, or all on one side with `absolute:true`

I'd like to a request an additional setting for aligning each bar in the vertical center.

A very basic display of what I mean:
![Group 3558](https://user-images.githubusercontent.com/11444698/149125653-70ee5c68-6ea2-4106-92fb-aa6fbcf87e5a.png)

**Comment by rutvik110** [comment]
yah, that's been on my mind as well. I might add it in the next update probably next week. Till then feel free to dive into source code to recreate that, if you do manage to get it then a PR is always welcome ☺️

**Comment by RebeccaWang0221** [comment]
@rutvik110 thank you for the awesome package! Is there still a plan to add this feature?

**Comment by rutvik110** [comment]
hey, yah it's still on the list. Just got delayed a bit more due to my other works. There will be some updates this month that'll include this.

**Comment by rutvik110** [comment]
Latest update of the package supports this now. 🚀🎉
https://pub.dev/packages/flutter_audio_waveforms/changelog
Please check it out! Closing the issue as this has been added.
