### ISSUE TITLE
Could allow active region to have inactive regions on both sides

### ISSUE THREAD

**Issue by sevenzees** [rutvik110/flutter_audio_waveforms#26]
It would be nice if you could set the active region to be in the middle, with inactive regions on both sides. This would allow using this package as a display for cropping a waveform.

![image](https://user-images.githubusercontent.com/39177575/178625749-d10cc4f0-6985-4f1f-aaf1-93ba1e21d303.png)

**Comment by rutvik110** [comment]
Wdym by cropping a waveform? Could you please share a bit more info?

**Comment by sevenzees** [comment]
Let's say a user has recorded some audio using their phone's microphone. There is probably some bad audio at the beginning and end of the recording. I would like to use this package to display the audio as a waveform and gray out the areas that the user is using some slider controls choose to crop off. Does that make sense?

**Comment by rutvik110** [comment]
Ohh! Got ya! 
I think you might not even have to use an active waveform in here. You could just add an overlay on top of the Waveform widget(like a stack) with some drag controls to determine overlay start-end position. And then you can basically just add an color filter to the overlay so anything below it has some filter added to it and give the in-active waveform an grey color?
Also another option would be to use a shadermask and define the start-end position of that shadermask rect for achieving that effect.

Apart from that, what you suggest is not in the scope of the package atm. Let me know if that helped.

**Comment by sevenzees** [comment]
Thank you, that helps!
