### ISSUE TITLE
export waveform image as PNG or JPG

### ISSUE THREAD

**Issue by t-m-z** [rutvik110/flutter_audio_waveforms#31]

**Comment by rutvik110** [comment]
This isn't the responsibility of the package right now considering what its use is intended for. You can either export waveform image directly with [audiowaveform](https://github.com/bbc/audiowaveform) or capture the waveform image in flutter using repaintboundary image capture technique.

Closing as this doesn't fall under package responsibility.

**Comment by t-m-z** [comment]
I still believe this is as a nice feature wish which could be usefull for e.g. decoding morse

**Comment by acastry** [comment]
> I still believe this is as a nice feature wish which could be usefull for e.g. decoding morse

you have the datas as an an arry you can export it to somewhere else to do what you want.
