### ISSUE TITLE
Can't able to run Provided Github code which is Provided by You,and write code for latest one 

### ISSUE THREAD

**Issue by AnkitFlutterDev** [rutvik110/flutter_audio_waveforms#45]
can't even run flutter pub get
get error like =>Because example depends on flutter_audio_waveforms from path which doesn't exist (could not
  find package flutter_audio_waveforms at
  "/Users/rutviktak/flutter_projects/flutter_plugins/flutter_audio_waveforms/"), version solving
  failed.

**Comment by rutvik110** [comment]
Local deps path is incorrect for `flutter_audio_waveforms`  as it mentions in the logged error,  `/Users/rutviktak/`. Either update it with relative/absolute path for `flutter_audio_waveforms` on your local system.

**Comment by rutvik110** [comment]
Closing as the issue should be resolved by updating the incorrect local path for `flutter_audio_waveforms` in pubspec.

**Comment by Qw1kow** [comment]
I can‘tI haven't solved the problem, can you tell me more about the solution
